theme = "semi-native"
icons = "awesome"

[[block]]
block = "battery"
interval = 10
format = " {percentage}"
full_format = " {percentage}"
hide_missing = true
driver = "sysfs"

[[block]]
block = "rofication"
interval = 1
socket_path = "/tmp/rofi_notification_daemon"

[[block]]
block = "sound"
driver = "pulseaudio"

[[block]]
block = "time"
interval = 5
format = "%m/%d %R"

